// UI-only dummy data for the alternative-view closer comparison table.
// Replace with real `outcome_log` aggregates later.

export const COMPARISON_ROWS = [
  {
    id: "ana",
    period: "thisWeek",
    name: "Ana",
    aov: 932,
    aoc: 251,
    sales: 9,
    closingRate: 26.5,
    pifRate: 33.3,
    showUpRate: 63.0,
    commission: 1285,
    goal: 81,
    recovered: 0,
    avatarUrl: null,
  },
  {
    id: "matias",
    period: "thisWeek",
    name: "Matias",
    aov: 709,
    aoc: 209,
    sales: 9,
    closingRate: 34.6,
    pifRate: 22.2,
    showUpRate: 53.1,
    commission: 1750,
    goal: 94,
    recovered: 0,
    avatarUrl: null,
  },
  {
    id: "daiana",
    period: "lastWeek",
    name: "Daiana",
    aov: 693,
    aoc: 185,
    sales: 5,
    closingRate: 35.7,
    pifRate: 0.0,
    showUpRate: 50.0,
    commission: 591,
    goal: 55,
    recovered: 0,
    avatarUrl: null,
  },
  {
    id: "emiliano",
    period: "lastWeek",
    name: "Emiliano",
    aov: 799,
    aoc: 220,
    sales: 2,
    closingRate: 16.7,
    pifRate: 0.0,
    showUpRate: 52.2,
    commission: 165,
    goal: 18,
    recovered: 0,
    avatarUrl: null,
  },
];
