// UI-only dummy data that mirrors the shape `CloserTodaysLeads` expects.
// No real DB calls — pure visual dataset.

export const SETTER_MAP = {
  s1: "Nilda",
  s2: "Marleen",
  s3: "Jenn",
  s4: "Malte",
};

export const DUMMY_LEADS = [
  {
    id: "ld-1",
    leads: {
      id: "lead-1",
      name: "RUBEN",
      email: "rubenparioty12@gmail.com",
      phone: "+34622169227",
    },
    setter_id: "s1",
    setters: { name: "Nilda" },
    call_date: "2026-04-29T19:14:00",
    book_date: "2026-04-29T18:50:00",
    picked_up: null,
    confirmed: null,
    showed_up: null,
    purchased: null,
    recovered: true,
    is_reschedule: false,
    cancelled: false,
    source_type: "ad",
    utm_campaign: "main",
    outcome_log: null,
    responseTimeMinutes: 5,
    called: true,
    no_show_state: null,
    closer_mc_id: null,
    manychat_user_id: null,
    closers: { name: "Matias" },
  },
  {
    id: "ld-2",
    leads: {
      id: "lead-2",
      name: "DONOVAN CRUZ",
      email: "donovan.cruz@example.com",
      phone: "+13373980175",
    },
    setter_id: "s1",
    setters: { name: "Nilda" },
    call_date: "2026-04-29T22:00:00",
    book_date: "2026-04-29T20:00:00",
    picked_up: true,
    confirmed: true,
    showed_up: true,
    purchased: null,
    recovered: false,
    is_reschedule: false,
    cancelled: false,
    source_type: "organic",
    utm_campaign: "dm-setter",
    outcome_log: null,
    responseTimeMinutes: 12,
    called: true,
    no_show_state: null,
    closer_mc_id: null,
    manychat_user_id: "mc-123",
    closers: { name: "Matias" },
  },
  {
    id: "ld-3",
    leads: {
      id: "lead-3",
      name: "JONATHAN BUENO",
      email: "jonathan@example.com",
      phone: "+14075094075",
    },
    setter_id: "s2",
    setters: { name: "Marleen" },
    call_date: "2026-04-29T22:30:00",
    book_date: "2026-04-29T22:00:00",
    picked_up: true,
    confirmed: true,
    showed_up: false,
    purchased: null,
    recovered: false,
    is_reschedule: true,
    cancelled: false,
    source_type: "ad",
    utm_campaign: "main",
    outcome_log: null,
    responseTimeMinutes: 18,
    called: true,
    no_show_state: "contacted",
    closer_mc_id: null,
    manychat_user_id: null,
    closers: { name: "Matias" },
  },
  {
    id: "ld-4",
    leads: {
      id: "lead-4",
      name: "EINER FAJARDO",
      email: "einer@example.com",
      phone: "+19189823983",
    },
    setter_id: "s3",
    setters: { name: "Jenn" },
    call_date: "2026-04-29T23:00:00",
    book_date: "2026-04-29T20:00:00",
    picked_up: true,
    confirmed: true,
    showed_up: true,
    purchased: true,
    recovered: false,
    is_reschedule: false,
    cancelled: false,
    source_type: "organic",
    utm_campaign: "ai-setting",
    outcome_log: null,
    responseTimeMinutes: 4,
    called: true,
    no_show_state: null,
    closer_mc_id: null,
    manychat_user_id: "mc-456",
    closers: { name: "Matias" },
  },
  {
    id: "ld-5",
    leads: {
      id: "lead-5",
      name: "LUIS DOMINGUEZ",
      email: "luis.d@example.com",
      phone: "+5215551234567",
    },
    setter_id: "s4",
    setters: { name: "Malte" },
    call_date: "2026-04-29T17:45:00",
    book_date: "2026-04-29T15:00:00",
    picked_up: false,
    confirmed: false,
    showed_up: false,
    purchased: null,
    recovered: false,
    is_reschedule: false,
    cancelled: false,
    source_type: "ad",
    utm_campaign: "main",
    outcome_log: null,
    responseTimeMinutes: 28,
    called: false,
    no_show_state: "no_show",
    closer_mc_id: null,
    manychat_user_id: null,
    closers: { name: "Matias" },
  },
];
